"""
TS-16 / TS-23 — Monthly Report Generator

Claude Haiku generates the report narrative HTML.
Puppeteer renders it to PDF via subprocess call to a Node.js script.

Report narrative sections (from TS-16):
  1. Summary — what happened this month in plain English
  2. Traffic — visitor volume, sources, trends vs last month
  3. Engagement — click-through rate, top content
  4. Attribution — what the data proves (honest about tier limitations)
  5. Commission savings — what was saved / estimated
  6. Social performance — posts published, top performers
  7. Recommendations — what to do next month

The Claude prompt is tier-aware:
  Tier 1: honest about click data only, clearly labels estimates
  Tier 2: confirms bookings, calculates true ROI
  Tier 3: full reconciliation with PMS, professional reporting
  Tier 4: notes self-reported data clearly

PDF is generated by puppeteer_renderer.js via subprocess.
Stored in Cloudflare R2 at reports/{client_id}/{property_id}/{year}-{month}.pdf
"""

import json
import logging
import os
import re
import subprocess
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import anthropic

from agents.agent7.models import (
    AnalyticsSnapshot,
    AttributionTier,
    MonthlyReport,
)

logger = logging.getLogger(__name__)

HAIKU_MODEL = "claude-haiku-4-5-20251001"
MAX_TOKENS  = 3000

PUPPETEER_SCRIPT = Path(__file__).parent / "puppeteer_renderer.js"


def generate_monthly_report(
    snapshot: AnalyticsSnapshot,
    property_name: str,
    property_id: str,
    client_id: str,
    report_month: str,       # "2026-03"
    anthropic_client: anthropic.Anthropic,
) -> MonthlyReport:
    """
    Generate the complete monthly report:
    1. Claude Haiku writes the narrative HTML
    2. HTML is assembled into a styled full-page report
    3. Puppeteer renders to PDF
    4. PDF uploaded to R2

    Returns MonthlyReport with all fields populated.
    """
    report = MonthlyReport(
        property_id=property_id,
        client_id=client_id,
        report_month=report_month,
        analytics=snapshot,
        generated_at=datetime.now(timezone.utc).isoformat(),
    )

    # ── Generate narrative HTML via Claude Haiku ──────────────────────────
    logger.info(f"[TS-23] Generating report narrative for property {property_id}")
    narrative_html = _generate_narrative(
        snapshot=snapshot,
        property_name=property_name,
        report_month=report_month,
        anthropic_client=anthropic_client,
    )
    report.narrative_html = narrative_html

    # ── Assemble full report HTML ─────────────────────────────────────────
    full_html = _build_report_html(
        property_name=property_name,
        report_month=report_month,
        snapshot=snapshot,
        narrative_html=narrative_html,
    )

    # ── Render to PDF via Puppeteer ───────────────────────────────────────
    logger.info(f"[TS-23] Rendering PDF for property {property_id}")
    pdf_bytes = _render_pdf(full_html, property_id, report_month)

    if pdf_bytes:
        # Upload to R2
        pdf_url = _upload_pdf_to_r2(
            pdf_bytes=pdf_bytes,
            client_id=client_id,
            property_id=property_id,
            report_month=report_month,
        )
        report.pdf_r2_url = pdf_url
        logger.info(f"[TS-23] PDF uploaded: {pdf_url}")
    else:
        logger.warning(f"[TS-23] PDF render failed for property {property_id}")

    return report


def _generate_narrative(
    snapshot: AnalyticsSnapshot,
    property_name: str,
    report_month: str,
    anthropic_client: anthropic.Anthropic,
) -> str:
    """Use Claude Haiku to write the monthly report narrative sections."""

    # Build tier-appropriate data summary for the prompt
    tier = snapshot.attribution_tier
    data_summary = _build_data_summary(snapshot)
    tier_context = _tier_context(tier)

    prompt = f"""Write a concise, professional monthly performance report narrative for a vacation rental property.

Property: {property_name}
Report month: {report_month}
Attribution tier: {tier.value}

{tier_context}

Performance data for this month:
{json.dumps(data_summary, indent=2)}

Write 6 short sections as HTML. Use <h3> for section titles, <p> for body text.
Be specific about numbers. Be honest about what the data proves vs estimates.
Sections:
1. Month Summary (2-3 sentences: what happened overall)
2. Traffic Performance (sessions, sources, trends)
3. Booking Activity (clicks, conversions if available, CTR)
4. Commission Savings (estimated or confirmed, clearly labelled)
5. Social Media Highlights (top platforms, best content)
6. Next Month Focus (1-2 specific recommendations)

Tone: Professional, direct, data-driven. No marketing language.
Write for a PMC who reads data, not marketing copy.
Return only the HTML sections, no wrapping document tags."""

    try:
        resp = anthropic_client.messages.create(
            model=HAIKU_MODEL,
            max_tokens=MAX_TOKENS,
            messages=[{"role": "user", "content": prompt}],
        )
        return resp.content[0].text.strip()
    except Exception as exc:
        logger.error(f"Report narrative generation failed: {exc}")
        return _fallback_narrative(snapshot, property_name, report_month)


def _build_data_summary(snapshot: AnalyticsSnapshot) -> dict:
    """Build a clean data dict for the Claude prompt."""
    summary: dict = {
        "sessions": snapshot.total_sessions,
        "unique_visitors": snapshot.unique_visitors,
        "booking_site_clicks": snapshot.total_booking_site_clicks,
        "click_through_rate_pct": round(snapshot.overall_ctr * 100, 2),
        "social_posts_published": snapshot.total_social_posts_published,
        "top_traffic_sources": [
            {"source": t.source.value, "sessions": t.sessions, "clicks": t.clicks_to_booking_site}
            for t in sorted(snapshot.traffic_by_source, key=lambda x: -x.sessions)[:4]
        ],
    }

    if snapshot.attribution_tier == AttributionTier.TIER_1_UTM:
        summary["estimated_bookings"] = snapshot.estimated_bookings_from_clicks
        summary["estimated_commission_saved_usd"] = snapshot.estimated_commission_saved
        summary["note"] = "Bookings and savings are estimates based on industry click-to-booking rate"

    if snapshot.pixel_active:
        summary["confirmed_bookings"] = snapshot.confirmed_bookings
        summary["confirmed_revenue_usd"] = snapshot.confirmed_revenue
        summary["confirmed_commission_saved_usd"] = snapshot.confirmed_commission_saved

    if snapshot.pms_connected:
        summary["pms_confirmed_bookings"] = snapshot.pms_confirmed_bookings
        summary["pms_total_revenue_usd"] = snapshot.pms_total_revenue
        summary["cancellation_rate_pct"] = round(snapshot.pms_cancellation_rate * 100, 1)
        summary["avg_booking_lead_time_days"] = snapshot.pms_avg_lead_time_days

    if snapshot.sessions_mom_pct is not None:
        summary["sessions_vs_last_month_pct"] = snapshot.sessions_mom_pct
    if snapshot.clicks_mom_pct is not None:
        summary["clicks_vs_last_month_pct"] = snapshot.clicks_mom_pct

    return summary


def _tier_context(tier: AttributionTier) -> str:
    """Return the tier-appropriate framing for the Claude prompt."""
    contexts = {
        AttributionTier.TIER_1_UTM: (
            "IMPORTANT: This property is on Tier 1 attribution (UTM clicks only). "
            "You can report traffic and clicks with confidence. "
            "Booking numbers are ESTIMATES only — label them as estimated, not confirmed. "
            "Do not overstate certainty. Be honest that confirmed bookings require the conversion pixel."
        ),
        AttributionTier.TIER_2_PIXEL: (
            "This property has the conversion pixel installed. "
            "You can report confirmed bookings and revenue directly from pixel data. "
            "State these as confirmed, not estimated."
        ),
        AttributionTier.TIER_3_PMS_API: (
            "This property has full PMS API integration. "
            "Report all booking data as fully reconciled — it comes directly from the PMS. "
            "Include cancellation rate and lead time data."
        ),
        AttributionTier.TIER_4_SELF_REPORT: (
            "This property is on self-reported attribution. "
            "Revenue data is provided by the PMC and is unverified. "
            "Label it clearly as self-reported."
        ),
    }
    return contexts.get(tier, "")


def _fallback_narrative(
    snapshot: AnalyticsSnapshot,
    property_name: str,
    report_month: str,
) -> str:
    """Fallback narrative when Claude is unavailable."""
    return f"""
<h3>Month Summary</h3>
<p>{property_name} generated {snapshot.total_sessions:,} page sessions in {report_month}
with {snapshot.total_booking_site_clicks:,} clicks to the booking site
(CTR: {snapshot.overall_ctr*100:.1f}%).</p>

<h3>Traffic Performance</h3>
<p>Total sessions: {snapshot.total_sessions:,}. Unique visitors: {snapshot.unique_visitors:,}.
Top source: {snapshot.traffic_by_source[0].source.value if snapshot.traffic_by_source else "N/A"}.</p>

<h3>Booking Activity</h3>
<p>Booking site clicks: {snapshot.total_booking_site_clicks:,}.
{f"Confirmed bookings: {snapshot.confirmed_bookings}." if snapshot.pixel_active else
 f"Estimated bookings: {snapshot.estimated_bookings_from_clicks:.0f} (estimated)."}</p>

<h3>Commission Savings</h3>
<p>{f"Confirmed commission saved: ${snapshot.confirmed_commission_saved:,.2f}." if snapshot.pixel_active else
   f"Estimated commission saved: ${snapshot.estimated_commission_saved:,.2f} (estimated based on click volume)."}</p>

<h3>Social Media</h3>
<p>{snapshot.total_social_posts_published} posts published this month.</p>

<h3>Next Month Focus</h3>
<p>Continue building social presence and drive direct booking traffic.</p>
"""


# ── Report HTML assembly ──────────────────────────────────────────────────

def _build_report_html(
    property_name: str,
    report_month: str,
    snapshot: AnalyticsSnapshot,
    narrative_html: str,
) -> str:
    """Assemble the styled full-page report HTML for Puppeteer rendering."""
    from calendar import month_name
    year, month_num = report_month.split("-")
    month_label = f"{month_name[int(month_num)]} {year}"

    # Attribution tier badge
    tier_labels = {
        AttributionTier.TIER_1_UTM: ("Tier 1 — Traffic & Clicks", "#3b82f6"),
        AttributionTier.TIER_2_PIXEL: ("Tier 2 — Confirmed Bookings", "#10b981"),
        AttributionTier.TIER_3_PMS_API: ("Tier 3 — Full Reconciliation", "#8b5cf6"),
        AttributionTier.TIER_4_SELF_REPORT: ("Tier 4 — Self-Reported", "#f59e0b"),
    }
    tier_label, tier_color = tier_labels.get(
        snapshot.attribution_tier, ("Unknown Tier", "#6b7280")
    )

    # Key metrics for the stats bar
    primary_metric_label = "Est. Commission Saved" if not snapshot.pixel_active else "Commission Saved"
    primary_metric_value = f"${snapshot.confirmed_commission_saved:,.0f}" if snapshot.pixel_active \
                           else f"${snapshot.estimated_commission_saved:,.0f}*"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Staylio Monthly Report — {property_name} — {month_label}</title>
  <style>
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{ font-family: 'Helvetica Neue', Arial, sans-serif; color: #1a1a1a;
           background: #fff; padding: 40px; font-size: 14px; line-height: 1.6; }}

    .header {{ border-bottom: 3px solid #1a1a1a; padding-bottom: 20px; margin-bottom: 30px; }}
    .header-top {{ display: flex; justify-content: space-between; align-items: flex-start; }}
    .staylio-brand {{ font-size: 11px; letter-spacing: 0.15em; text-transform: uppercase;
                     color: #666; margin-bottom: 8px; }}
    h1 {{ font-size: 28px; font-weight: 300; margin-bottom: 4px; }}
    .report-period {{ font-size: 16px; color: #666; }}
    .tier-badge {{ display: inline-block; padding: 4px 12px; border-radius: 4px;
                   font-size: 11px; font-weight: 600; letter-spacing: 0.05em;
                   background: {tier_color}20; color: {tier_color}; border: 1px solid {tier_color}40; }}

    .stats-bar {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 1px;
                  background: #e5e5e5; border: 1px solid #e5e5e5;
                  margin-bottom: 30px; }}
    .stat-cell {{ background: #fff; padding: 16px 20px; }}
    .stat-label {{ font-size: 11px; text-transform: uppercase; letter-spacing: 0.1em;
                   color: #888; margin-bottom: 4px; }}
    .stat-value {{ font-size: 24px; font-weight: 600; color: #1a1a1a; }}
    .stat-note  {{ font-size: 10px; color: #aaa; margin-top: 2px; }}

    .narrative {{ margin-bottom: 30px; }}
    .narrative h3 {{ font-size: 13px; font-weight: 700; text-transform: uppercase;
                     letter-spacing: 0.08em; color: #444; margin: 20px 0 8px;
                     border-bottom: 1px solid #eee; padding-bottom: 6px; }}
    .narrative p {{ margin-bottom: 8px; color: #333; }}

    .footer {{ border-top: 1px solid #eee; padding-top: 16px; margin-top: 30px;
               display: flex; justify-content: space-between; font-size: 11px; color: #aaa; }}
    .estimate-note {{ font-size: 10px; color: #aaa; margin-top: 8px; font-style: italic; }}
  </style>
</head>
<body>

  <div class="header">
    <div class="header-top">
      <div>
        <p class="staylio-brand">Staylio Monthly Performance Report</p>
        <h1>{property_name}</h1>
        <p class="report-period">{month_label}</p>
      </div>
      <span class="tier-badge">{tier_label}</span>
    </div>
  </div>

  <div class="stats-bar">
    <div class="stat-cell">
      <div class="stat-label">Page Sessions</div>
      <div class="stat-value">{snapshot.total_sessions:,}</div>
      {f'<div class="stat-note">{"+" if (snapshot.sessions_mom_pct or 0) >= 0 else ""}{snapshot.sessions_mom_pct:.0f}% vs last month</div>' if snapshot.sessions_mom_pct is not None else ""}
    </div>
    <div class="stat-cell">
      <div class="stat-label">Booking Clicks</div>
      <div class="stat-value">{snapshot.total_booking_site_clicks:,}</div>
      <div class="stat-note">CTR: {snapshot.overall_ctr*100:.1f}%</div>
    </div>
    <div class="stat-cell">
      <div class="stat-label">{"Confirmed Bookings" if snapshot.pixel_active else "Est. Bookings"}</div>
      <div class="stat-value">{snapshot.confirmed_bookings if snapshot.pixel_active else f"{snapshot.estimated_bookings_from_clicks:.0f}"}</div>
      {"" if snapshot.pixel_active else '<div class="stat-note">Estimated from click volume</div>'}
    </div>
    <div class="stat-cell">
      <div class="stat-label">{primary_metric_label}</div>
      <div class="stat-value">{primary_metric_value}</div>
      {"" if snapshot.pixel_active else '<div class="stat-note">*Based on industry booking rate</div>'}
    </div>
  </div>

  <div class="narrative">
    {narrative_html}
  </div>

  {"<p class='estimate-note'>* Estimated values use a 2% click-to-booking rate and average nightly rate. Install the conversion pixel for confirmed booking data.</p>" if not snapshot.pixel_active else ""}

  <div class="footer">
    <span>Staylio · staylio.ai</span>
    <span>Generated {datetime.now(timezone.utc).strftime("%B %d, %Y")}</span>
    <span>Confidential — {property_name}</span>
  </div>

</body>
</html>"""


# ── Puppeteer PDF rendering ───────────────────────────────────────────────

def _render_pdf(html_content: str, property_id: str, report_month: str) -> Optional[bytes]:
    """
    Render HTML to PDF via Puppeteer (Node.js subprocess).
    Writes HTML to a temp file, calls puppeteer_renderer.js,
    reads the PDF output and returns bytes.
    """
    if not PUPPETEER_SCRIPT.exists():
        logger.error(f"[TS-23] Puppeteer renderer not found at {PUPPETEER_SCRIPT}")
        return None

    try:
        with tempfile.NamedTemporaryFile(
            suffix=".html", mode="w", encoding="utf-8", delete=False
        ) as html_file:
            html_file.write(html_content)
            html_path = html_file.name

        with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as pdf_file:
            pdf_path = pdf_file.name

        result = subprocess.run(
            ["node", str(PUPPETEER_SCRIPT), html_path, pdf_path],
            capture_output=True,
            text=True,
            timeout=60,
        )

        if result.returncode != 0:
            logger.error(f"[TS-23] Puppeteer failed: {result.stderr[:300]}")
            return None

        with open(pdf_path, "rb") as f:
            return f.read()

    except subprocess.TimeoutExpired:
        logger.error(f"[TS-23] Puppeteer timed out for property {property_id}")
        return None
    except Exception as exc:
        logger.error(f"[TS-23] PDF render error: {exc}")
        return None
    finally:
        import os as _os
        for path in (html_path, pdf_path):
            try:
                _os.unlink(path)
            except Exception:
                pass


def _upload_pdf_to_r2(
    pdf_bytes: bytes,
    client_id: str,
    property_id: str,
    report_month: str,
) -> Optional[str]:
    """Upload the rendered PDF to Cloudflare R2."""
    try:
        from agents.agent3.r2_storage import _get_r2_client, R2_PUBLIC_BASE
        key = f"reports/{client_id}/{property_id}/{report_month}.pdf"
        bucket = "staylio-reports"
        client = _get_r2_client()
        client.put_object(
            Bucket=bucket,
            Key=key,
            Body=pdf_bytes,
            ContentType="application/pdf",
            CacheControl="private, no-cache",
        )
        return f"{R2_PUBLIC_BASE}/reports/{key}"
    except Exception as exc:
        logger.error(f"[TS-23] R2 PDF upload failed: {exc}")
        return None
